### ISSUE TITLE
The PDF time report does not contain the amount of time spent or the description.

### ISSUE THREAD

**Issue by JonDeG** [Project-Pier/ProjectPier-Plugin-Time#3]
Each time entry generates an item in the PDF report but the information being reported in nonsensical and useless.
![pdf-report-nonsense](https://cloud.githubusercontent.com/assets/2878315/5693482/810f4636-98ec-11e4-98c7-51b8a7db463d.jpg)

**Comment by Engelbert** [comment]
I've been researching this issue, I reckon I can come up with a nice solution. 

![screenshot from 2015-01-12 23 20 07](https://cloud.githubusercontent.com/assets/755439/5712340/c05af404-9ab1-11e4-8f46-47e927ed3aa0.png)

Something like this should do for now though. I've got the code locally, I'll get a testable branch up somewhere tomorrow.

**Comment by Engelbert** [comment]
@JonDeG Here is another version of the times pdf report.
![screenshot from 2015-01-14 16 28 51](https://cloud.githubusercontent.com/assets/755439/5741391/1421624e-9c0b-11e4-81ad-99f69359e302.png)
The info is no longer made up of useless things. 
The whole document is using subtle colours (that are perfectly printable in B&W) to make it easier to see what is what.
The layout of the document is different too, but it makes it easier to see things IMO.
Any comments, remarks, tips, ... ?
